FROM almalinux:latest AS builder
ENV APP_NAME=${APP_NAME} \
    APP_ICON_URL=${APP_ICON_URL} \
    NO_STRIP=1 \
    APPIMAGE_EXTRACT_AND_RUN=1 \
    ARCH=x86_64

WORKDIR /app
COPY app.rpm .

RUN dnf install -y epel-release && \
    dnf update -y && \
    dnf install -y wget findutils grep ./app.rpm && \
    dnf clean all -y && \
    rm -rf /var/cache/dnf /tmp/* /var/log/dnf.*



    # Download linuxdeploy and GTK plugin (x86_64)
RUN wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
    -O /usr/local/bin/linuxdeploy && \
    chmod +x /usr/local/bin/linuxdeploy

RUN wget -q https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh \
    -O /usr/local/bin/linuxdeploy-plugin-gtk.sh && \
    chmod +x /usr/local/bin/linuxdeploy-plugin-gtk.sh

WORKDIR /app

ENV APPIMAGE_EXTRACT_AND_RUN=1
ENV ARCH=x86_64
RUN OUTPUT=rpm_app.AppImage \
    /usr/local/bin/linuxdeploy \
      --appdir AppDir \
      --executable AppDir/usr/bin/QCADesigner \
      --desktop-file AppDir/usr/share/applications/*.desktop \
      --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/*.png \
      --output appimage && \
    test -f /app/rpm_app.AppImage
