FROM almalinux:latest AS builder

ARG APP_NAME
ENV APP_NAME=${APP_NAME} \
    NO_STRIP=1 \
    APPIMAGE_EXTRACT_AND_RUN=1 \
    ARCH=x86_64

WORKDIR /app
COPY app.rpm .

RUN dnf install -y epel-release && \
    dnf update -y && \
    dnf install -y wget findutils grep cpio ./app.rpm && \
    dnf clean all -y && \
    rm -rf /var/cache/dnf /tmp/* /var/log/dnf.*

RUN wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
    -O /usr/local/bin/linuxdeploy && \
    chmod +x /usr/local/bin/linuxdeploy

RUN wget -q https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh \
    -O /usr/local/bin/linuxdeploy-plugin-gtk.sh && \
    chmod +x /usr/local/bin/linuxdeploy-plugin-gtk.sh

WORKDIR /app

RUN mkdir -p AppDir && \
    cd AppDir && \
    rpm2cpio /app/app.rpm | cpio -idmv

RUN OUTPUT=rpm_app.AppImage \
    /usr/local/bin/linuxdeploy \
      --appdir AppDir \
      --executable "AppDir/usr/bin/${APP_NAME}" \
      --desktop-file AppDir/usr/share/applications/[a-zA-Z]*.desktop \
      --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/[a-zA-Z]*.png \
      --output appimage && \
    mkdir -p /output && \
    mv rpm_app.AppImage /output/ && \
    test -f /output/rpm_app.AppImage
