name: cleanup
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list --json databaseId  -q '.[].databaseId' | xargs -IID gh api    \
          "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID"  \
          -X DELETE
